### ISSUE TITLE
AttributeError: 'module' object has no attribute 'shape' if chunk not in yaml file

### ISSUE THREAD

**Issue by Swarchal** [CarragherLab/cptools2#24]
```
** parsing config file 'BH_test_config.yaml'
Traceback (most recent call last):
  File "/exports/applications/apps/SL7/python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/exports/applications/apps/SL7/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 90, in <module>
    main()
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 84, in main
    configure_job(config)
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 50, in configure_job
    jobber.create_commands(**config.create_command_args)
  File "build/bdist.linux-x86_64/egg/cptools2/job.py", line 151, in create_commands
    self._create_loaddata(job_size)
  File "build/bdist.linux-x86_64/egg/cptools2/job.py", line 128, in _create_loaddata
    loaddata.check_dataframe_size(loaddata, job_size)
  File "build/bdist.linux-x86_64/egg/cptools2/loaddata.py", line 110, in check_dataframe_size
    nrow = dataframe.shape[0]
AttributeError: 'module' object has no attribute 'shape'
```

**Comment by Swarchal** [comment]
If `check_dataframe_size` is removed then errors with the following:

```
** parsing config file ''
** creating output directories at ''
** detected 6 plates in experiment
	 1. FLO1
Traceback (most recent call last):
  File "/exports/applications/apps/SL7/python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/exports/applications/apps/SL7/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 90, in <module>
    main()
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 84, in main
    configure_job(config)
  File "/gpfs/igmmfs01/eddie/Drug-Discovery/scott/tmp/cptools2/cptools2/__main__.py", line 50, in configure_job
    jobber.create_commands(**config.create_command_args)
  File "build/bdist.linux-x86_64/egg/cptools2/job.py", line 178, in create_commands
    dataframe=dataframe)
  File "build/bdist.linux-x86_64/egg/cptools2/commands.py", line 52, in write_loaddata
    dataframe = utils.prefix_filepaths(dataframe, name, location)
  File "build/bdist.linux-x86_64/egg/cptools2/utils.py", line 68, in prefix_filepaths
    path_cols = [col for col in dataframe.columns if col.startswith("PathName")]
AttributeError: 'str' object has no attribute 'columns'
```
